# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 309893490c007690a23494956ec4040da7777c74e64e9739c01ec19741b3224f0003813548d4279804e3f8caf7417d182dfbd7ac6fbefee0a36f1d9d48ac03d3

test:
  secret_key_base: df4b4374b30043a0431cf9abb9b5a9e1aefa051b204a8f8f15570b282906ea29f56f4be416d2e5d459e5d9205d965d2e7080772e5179ae781387092202819fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
